# GWEI CONTROL
GAS_MULTIPLAYER = 1

# PROXY MODE
USE_PROXY = False # True or False

# REMOVE A WALLET FROM THE LIST AFTER THE JOB IS DONE
RANDOM_WALLET = True # True or False

# SLEEP AFTER DONE
SLEEP_FROM = 30  # Second
SLEEP_TO = 60  # Second

# THREAD CONTROL
QUANTITY_THREADS = 1
THREAD_SLEEP_FROM = 5 # Second
THREAD_SLEEP_TO = 15 # Second

SLIPPAGE = 1 # %

# DEBUG MODE
DEBUG_MODE = True # True or False