# GWEI CONTROL
GAS_MULTIPLAYER = 1

# PROXY MODE
USE_PROXY = False

# TAKE THE WALLETS IN RANDOM ORDER
RANDOM_WALLET = True

# SLEEP AFTER DONE
SLEEP_FROM = 30  # Seconds
SLEEP_TO = 60  # Seconds

# THREAD CONTROL
QUANTITY_THREADS = 1
THREAD_SLEEP_FROM = 5 # Seconds
THREAD_SLEEP_TO = 15 # Seconds

# SLIPPAGE FOR SWAPS
SLIPPAGE = 1

# DEBUG MODE
DEBUG_MODE = False
